
spring.application.name=AurusDataSyncHub
server.port=1234
app.data.file=/AurusDataSyncHub/data/data.json

transaction.urls.DEV=https://qa42.auruspay.com/auruspay/api/auruspayServices/transactionService
transaction.urls.CERT=https://stgcrt.auruspay.com/auruspay/api/auruspayServices/transactionService
transaction.urls.SGND=https://sgnd42.auruspay.com/auruspay/api/auruspayServices/transactionService
transaction.urls.LDND=https://ldnd42.auruspay.com/auruspay/api/auruspayServices/transactionService
transaction.urls.UAT=https://uat42.auruspay.com/auruspay/api/auruspayServices/transactionService
transaction.urls.CHX=http://192.168.180.54:8080/auruspay/api/auruspayServices/transactionService

